#!/bin/bash
echo "🏨 Hotel Management System - Quick Access Links"
echo "=============================================="
echo ""
echo "🌐 Main Portal:          http://localhost:8000"
echo "🆕 Registration:         http://localhost:8000/registration/"
echo "👤 Hotel Manager:        http://localhost:8000/hotel-manager/"
echo "🛡️ Admin Portal:         http://localhost:8000/admin/"
echo "🏛️ Pemda Dashboard:      http://localhost:8000/admin/pemda/"
echo "🏛️ Pusat Dashboard:      http://localhost:8000/admin/pusat/"
echo ""
echo "🚀 To start development server:"
echo "   ./start-dev.sh"
echo ""
echo "📱 Mobile testing:"
echo "   http://[your-ip]:8000"
