version: '3.8'

services:
  mice-id-inventory:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mice-id-inventory
    restart: unless-stopped
    ports:
      - "3000:3000"
    # Adding health check
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    # Environment variables if needed
    environment:
      - NODE_ENV=production